# Generated by Django 3.2 on 2021-04-28 10:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('type', models.CharField(choices=[('cow', 'Коворкинг'), ('flr', 'Этаж')], default='cow', help_text='Тип площадки', max_length=3)),
                ('map_url', models.CharField(help_text='Карта площадки', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('short_name', models.CharField(help_text='Короткое наименование', max_length=100)),
                ('full_name', models.CharField(help_text='Полное наименование', max_length=250)),
                ('code', models.PositiveBigIntegerField(default=0, help_text='Код ЦФО')),
                ('root_dir', models.CharField(help_text='Каталог со статикой', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('area', models.ForeignKey(blank=True, default=None, help_text='Родительская площадка', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.resource')),
                ('location', models.TextField(blank=True, help_text='Описание расположения', null=True)),
                ('description', models.TextField(blank=True, help_text='Общее описание', null=True)),
                ('capacity', models.SmallIntegerField(default=0, help_text='Количество сидячих мест')),
                ('has_av', models.BooleanField(default=False, help_text='Наличие аудио/видео аппаратуры')),
                ('has_phone', models.BooleanField(default=False, help_text='Наличие телефона')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.resource',),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания')),
                ('created_by', models.CharField(default='', help_text='Кем создано', max_length=50)),
                ('message', models.CharField(help_text='Сообщение', max_length=500)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('resource', models.ForeignKey(blank=True, default=None, help_text='Объект запроса', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('message', models.CharField(help_text='Сообщение', max_length=500)),
                ('start', models.DateTimeField(blank=True, help_text='Начало брони')),
                ('finish', models.DateTimeField(blank=True, help_text='Окончание брони')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('users_group', models.ForeignKey(blank=True, default=None, help_text='Группа', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('middle_name', models.CharField(help_text='Отчество', max_length=500)),
                ('company', models.ForeignKey(blank=True, default=None, help_text='Компания', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('def_area', models.ForeignKey(blank=True, default=None, help_text='Площадка по умолчанию', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('description', models.CharField(help_text='Описание', max_length=500)),
                ('users', models.ManyToManyField(blank=True, default=None, help_text='Участники', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания')),
                ('created_by', models.CharField(default='', help_text='Кем создано', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now=True, help_text='Время изменения')),
                ('changed_by', models.CharField(default='', help_text='Кем изменено', max_length=50)),
                ('start_ts', models.DateTimeField(help_text='Начало брони')),
                ('end_ts', models.DateTimeField(help_text='Окончание брони')),
                ('confirmed', models.BooleanField(blank=True, default=False, help_text='Подтверждение брони')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Время изменения', null=True)),
                ('confirmed_by', models.CharField(blank=True, default='', help_text='Кем подтверждено', max_length=50, null=True)),
                ('pin', models.PositiveSmallIntegerField(default=main.utils.get_pin, help_text='PIN-код')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('event', models.ForeignKey(blank=True, default=None, help_text='Событие', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('resource', models.ForeignKey(blank=True, default=None, help_text='Объект бронирования', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resource')),
                ('user', models.ForeignKey(default=None, help_text='Бронирующий', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='company',
            field=models.ForeignKey(blank=True, default=None, help_text='Компания', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.resource')),
                ('persisted', models.BooleanField(blank=True, default=False, help_text='Постоянное место')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='За кем закреплено', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.resource',),
        ),
    ]
