# Generated by Django 3.2 on 2021-04-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='def_area',
            field=models.ForeignKey(blank=True, default=None, help_text='Площадка по умолчанию', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area'),
        ),
    ]
